### ISSUE TITLE
对单独的个人进行告警失败，还是告警了所有人。

### ISSUE THREAD

**Issue by 20has** [anjia0532/elastalert-wechat-plugin#11]
![图片](https://user-images.githubusercontent.com/8327740/54796178-24e9a300-4c8a-11e9-997c-d63801da753f.png)
你好，我把微信告警插件放在elastalert目录下就可以工作了。
但是目前遇到个问题，我想对企业微信部门内 不同的几个的user_id进行告警通知却不成功，还是对整个部门内成员@all进行了通知。
部分设置 如下：
party_id: 19
user_id: "zhangsna|wangwu"
#user_id: "@all"
#tag_id: 1

**Comment by anjia0532** [comment]
你的用法有问题，你要推送给id为19的部门，以及id为张三和王五的用户，是并集，不是交集。
如果只想推给张三和王五，把party_id去掉。另外，不建议用party_id和user_id,用tag_id会更灵活
