### ISSUE TITLE
token缓存建议

### ISSUE THREAD

**Issue by qhh0205** [anjia0532/elastalert-wechat-plugin#4]
你好，看了下您微信发送代码，发现没有缓存token逻辑，我建议可以加个token 缓存逻辑，我是将token 缓存到了redis，可以参考下我实现的:
https://gitlab.com/pythoner/wechat-alert
我抽空给提一下代码。

**Comment by anjia0532** [comment]
有缓存token啊，详见
https://github.com/anjia0532/elastalert-wechat-plugin/blob/master/wechat_qiye_alert.py#L37

https://github.com/anjia0532/elastalert-wechat-plugin/blob/master/wechat_qiye_alert.py#L66-L67

https://github.com/anjia0532/elastalert-wechat-plugin/blob/master/wechat_qiye_alert.py#L86-L87

**Comment by anjia0532** [comment]
看了一下你的代码，依赖redis进行的缓存token，但是对于本插件来说，太重了。需要依赖redis。

但是你的方案在一个企业号，多个应用共享access_token时是有意义的。相关替代方案很多。原理是一样的，有一个外置服务，缓存了access_token，然后各应用按需获取。

我对python操作redis不太熟悉，只从代码你的字面看是使用了连接池（但是没看到有设置池大小和长连接超时时间的代码），需要考虑一下高频情况下可能引起的操作redis的损耗情况

access_token缓存的意义又两点，1，减少取token的一次http请求损耗的资源，2，微信限制access_token一天的获取次数。

假设使用本插件报警的频率不高，低于3000次/日，其实完全可以不操心缓存问题(注意该企业号的其他应用可能存在的获取的access_token)。

一个access_token是7200s有效，所以使用了我的代码缓存策略，一天会获取0-(12|13)次access_token（如果一天不报警则0次，如果每小时都报警，因为需要提前续期会存在13次请求）
