### ISSUE TITLE
微信发送失败

### ISSUE THREAD

**Issue by Hello-Linux** [anjia0532/elastalert-wechat-plugin#9]
INFO:elastalert:send msg and response: {"errcode":301002,"errmsg":"not allow operate another agent with this accesstoken., hint: [1548747708_3_16b54f832165a68be9c08eca7524f7e0], more info at https://open.work.weixin.qq.com/devtool/query?e=301002"}

**Comment by anjia0532** [comment]
https://open.work.weixin.qq.com/devtool/query?e=301002 你配置有问题啊
